### ISSUE TITLE
Zappr file not compliant

### ISSUE THREAD

**Issue by ZroMnc** [zalando-zmon/zmon-slo-metrics#34]
Your [Zappr file](https://github.com/zalando-zmon/service-level-reporting/blob/master/.zappr.yaml) does not yield the correct config.

Consider doing this
```yaml
X-Zalando-Team: "zmon"
X-Zalando-Type: code

approvals:
  minimum: 2

commit:
  message:
    patterns: # commit message has to match any one of
      - "^ *#[0-9]+" # starts with hash and digits
```
