### ISSUE TITLE
Fix securityDefinitions in the API spec

### ISSUE THREAD

**Issue by lmineiro** [zalando-zmon/zmon-slo-metrics#39]
The current swagger spec contains only the example securityDefinitions
```
securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
```
Which suggests a wrong flow is specified.
